#!/usr/bin/env bash
echo "# Helper to export env variables for recurring plans (if already created)"
echo "# Example usage: ./scripts/export_price_envs.sh"

echo "VITE_STRIPE_PRICE_STARTER_SPARK_MONTHLY=${VITE_STRIPE_PRICE_STARTER_SPARK_MONTHLY:-}";
echo "VITE_STRIPE_PRICE_STARTER_SPARK_YEARLY=${VITE_STRIPE_PRICE_STARTER_SPARK_YEARLY:-}";
echo "VITE_STRIPE_PRICE_BRAND_PULSE_MONTHLY=${VITE_STRIPE_PRICE_BRAND_PULSE_MONTHLY:-}";
echo "VITE_STRIPE_PRICE_BRAND_PULSE_YEARLY=${VITE_STRIPE_PRICE_BRAND_PULSE_YEARLY:-}";
echo "VITE_STRIPE_PRICE_IMPACT_ENGINE_MONTHLY=${VITE_STRIPE_PRICE_IMPACT_ENGINE_MONTHLY:-}";
echo "VITE_STRIPE_PRICE_IMPACT_ENGINE_YEARLY=${VITE_STRIPE_PRICE_IMPACT_ENGINE_YEARLY:-}";
